SELECT * FROM LECTURA;
SELECT * FROM PAGOCONSUMO;
SELECT * FROM MEDIDOR;

SELECT U.NOMBRE,U.PATERNO,M.MONTO,M.FECHA, M.MES,M.AÑO
FROM USUARIO U, PAGOCONSUMO M, MEDIDOR T
WHERE U.nroMed=T.nroMed AND T.nroMed=M.nroMed  ORDER BY U.nombre DESC;
